# Basic `dependabot.yml` file with

version: 2
updates:
  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check the actions for updates every week
    schedule:
      interval: "weekly"