default:
  image: public.ecr.aws/docker/library/node:18-bullseye
  tags:
    - size:2xlarge
    - arch:amd64

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_REF_NAME == "main"
      when: always
    - when: never

# Check merge request message
title-lint:
  stage: .pre
  script:
    - echo Start PR Validation
    - env
    - '[[ "$CI_COMMIT_MESSAGE" =~ ^(feat|fix|chore|docs|tests|ci) ]] || (echo "no commit type is specified in merge request title" && exit 1)'

# Check code format issue
code-format:
  stage: .pre
  script:
    - npm run format

# Check code lint issue
code-lint:
  stage: .pre
  script:
    - npm i
    - npm run lint

build:
  stage: build
  before_script:
    - npm i
  script:
    - npm run build
    - npm run test

